# azure-cosmos-cassandra-driver-3-extensions build pipeline
# Builds and runs tests with Apache Maven.
# Reference: https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- release/java-driver-3/*

pr:
- master
- release/java-driver-3/*

variables:

- name: Log.Filename
  value: $(Build.ArtifactStagingDirectory)/azure-cosmos-cassandra-driver-3.log
  readonly: true

- name: Reporting.Directory
  value: $(Build.ArtifactStagingDirectory)
  readonly: true

- name: Package.ArgLine
  value: >
    -Dazure.cosmos.cassandra.log-file='$(Log.Filename)'
    -Dazure.cosmos.cassandra.reporting-directory='$(Reporting.Directory)'
    -Dazure.cosmos.cassandra.contact-point='$(AZURE_COSMOS_CASSANDRA_CONTACT_POINT)'
    -Dazure.cosmos.cassandra.username='$(AZURE_COSMOS_CASSANDRA_USERNAME)'
    -Dazure.cosmos.cassandra.password='$(AZURE_COSMOS_CASSANDRA_PASSWORD)'
    -Dazure.cosmos.cassandra.global-endpoint='$(AZURE_COSMOS_CASSANDRA_GLOBAL_ENDPOINT)'
    -Dazure.cosmos.cassandra.local-datacenter='$(AZURE_COSMOS_CASSANDRA_LOCAL_DATACENTER)'
    -Dazure.cosmos.cassandra.read-datacenter='$(AZURE_COSMOS_CASSANDRA_READ_DATACENTER)'
    -Dazure.cosmos.cassandra.write-datacenter='$(AZURE_COSMOS_CASSANDRA_WRITE_DATACENTER)'
    -Dazure.cosmos.cassandra.nodes='$(AZURE_COSMOS_CASSANDRA_NODES)'
  readonly: true

- name: Examples.ArgLine
  value: $(Package.ArgLine)
  readonly: true

- name: Stage-Artifacts
  value: |
    $packageName = [System.IO.Path]::GetFileNameWithoutExtension($(Get-Item *.jar -Exclude *-sources.jar,*-javadoc.jar).Name)
    $targetDirectory = New-Item -ItemType Directory $Env:BUILD_ARTIFACTSTAGINGDIRECTORY/$packageName

    Copy-Item *.jar $targetDirectory
    Copy-Item ../pom.xml $targetDirectory/$packageName.pom

    $packageName = $packageName.Split("-extensions-") -join "-"
    $targetDirectory = New-Item -ItemType Directory $Env:BUILD_ARTIFACTSTAGINGDIRECTORY/$packageName

    Copy-Item ../../pom.xml $targetDirectory/$packageName.pom
  readonly: true

jobs:

- job: Build_with_Java_8
  strategy:
    matrix:
      Linux:
        ImageName: 'ubuntu-latest'
      MacOS:
        ImageName: 'macos-latest'
      Windows:
        ImageName: 'windows-latest'
    maxParallel: 1
  pool:
    vmImage: $(ImageName)
  steps:
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'help:active-profiles install javadoc:test-javadoc'
      findBugsRunAnalysis: true
      options: '-DskipTests'
  - task: Maven@3
    displayName: 'Verify package'
    inputs:
      mavenPomFile: 'package/pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'verify'
      options: '-DargLine="$(Package.ArgLine)"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: Maven@3
    displayName: 'Verify examples'
    inputs:
      mavenPomFile: 'examples/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: '-DargLine="$(Examples.ArgLine)"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: PowerShell@2
    displayName: 'Stage artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/package/target'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish staged artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'driver-3.java-8.$(ImageName)'
      publishLocation: 'pipeline'

- job: Build_with_Java_11
  strategy:
    matrix:
      Linux:
        ImageName: 'ubuntu-latest'
      MacOS:
        ImageName: 'macos-latest'
      Windows:
        ImageName: 'windows-latest'
    maxParallel: 1
  pool:
    vmImage: $(ImageName)
  steps:
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'help:active-profiles install javadoc:test-javadoc'
      findBugsRunAnalysis: true
      options: '-DskipTests'
  - task: Maven@3
    displayName: 'Verify package'
    inputs:
      mavenPomFile: 'package/pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'verify'
      options: '-DargLine="$(Package.ArgLine)"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: Maven@3
    displayName: 'Verify examples'
    inputs:
      mavenPomFile: 'examples/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: '-DargLine="$(Examples.ArgLine)"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: PowerShell@2
    displayName: 'Stage artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/package/target'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish staged artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'driver-3.java-11.$(ImageName)'
      publishLocation: 'pipeline'
