# azure-cosmos-cassandra-driver-4-extensions build pipeline
# Builds and runs tests with Apache Maven.
# Reference: https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop/java-driver-4
- release/java-driver-4/*

pr:
- develop/java-driver-4
- release/java-driver-4/*

variables:

- name: Azure.Cosmos.Cassandra.Preferred.Regions
  value: '$(AZURE_COSMOS_CASSANDRA_PREFERRED_REGION_1),$(AZURE_COSMOS_CASSANDRA_PREFERRED_REGION_2),$(AZURE_COSMOS_CASSANDRA_PREFERRED_REGION_3)'
  readonly: true

- name: Azure.Cosmos.Cassandra.Truststore.Content
  value: >
    /u3+7QAAAAIAAAABAAAAAgAzY29zbW9zLWNhc3NhbmRyYS0zLmNhc3NhbmRyYS5j
    b3Ntb3MuYXp1cmUuY29tOjEwMzUwAAABfcALYgwABVguNTA5AAAJUjCCCU4wggc2
    oAMCAQICExIAGW3/XxPy2iMMX4EAAAAZbf8wDQYJKoZIhvcNAQELBQAwTzELMAkG
    A1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEgMB4GA1UE
    AxMXTWljcm9zb2Z0IFJTQSBUTFMgQ0EgMDEwHhcNMjExMDAzMDIxODQ2WhcNMjIx
    MDAzMDIxODQ2WjAlMSMwIQYDVQQDDBoqLnRhYmxlLmNvc21vc2RiLmF6dXJlLmNv
    bTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMsa+oG6N8a7jPJTDqRn
    ttuBAmlR5nsooA1C2FbetRvTydz2QP7nkKU33HWuWpysCJOldZj6I9zrVXVU2ICs
    jA3FXs5q1iy5X0toOZD6tkAnNX9n7AxpWC4CM3F9eRJTtW6phkYDFHkduR/7PWgn
    06VSaAQSMDsx9hM4Kqa9W88aokWMFyG73Aes8VaZfENfDIxhHpdbkGOMJcqnv+Jv
    glrclhvH42R772EmSbh3M85uc/DTAwfliNeEbRTPDvpthBttIvLzJWDveJwH2Ifj
    pmd4XxOH2Va2Ox+Rc0p52G6QGmPYukqfOiRIAsX0GWamSYqWJfdYZMPyhzXq1jgD
    hTkCAwEAAaOCBUswggVHMIIBfwYKKwYBBAHWeQIEAgSCAW8EggFrAWkAdgApeb7w
    njk5IfBWc59jpXflvld9nGAK+PlNXSZcJV3HhAAAAXxD+4nFAAAEAwBHMEUCIBYl
    +DMnL396WLrgKZ1YjQcaqsZAb0DeNT+l7W/ugQyaAiEAuTdl82EKo6RMURBT9wHo
    Y7uHsuAGFfVhgKgUvfHuH6gAdgBVgdTCFpA2AUrqC5tXPFPwwOQ4eHAlCBcvo6od
    BxPTDAAAAXxD+4qnAAAEAwBHMEUCIQCz8adYL7qF4wwR0EjXoaYFISEFVG1xRYEd
    eLFXWXVpSAIgAOyUcRXYV1aCN0eKOHpKhGiZHUnBaUJPLPtZiB4IoO8AdwBByMqx
    3yJGShDGoToJQodeTjGLGwPr60vHaPCQYpYG9gAAAXxD+4nIAAAEAwBIMEYCIQCZ
    x+YAqAaKTdUAC/h0lmE5SrtqmUrhAyqo5Tz31YZyQAIhAILDBRKU6/aiHoEtpLdl
    ez5IvdLLVQAF0SvyOAMNRL+MMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwEw
    CgYIKwYBBQUHAwIwPgYJKwYBBAGCNxUHBDEwLwYnKwYBBAGCNxUIh9qGdYPu2QGC
    yYUbgbWeYYX062CBXYWGjkGHwphQAgFkAgEnMIGHBggrBgEFBQcBAQR7MHkwUwYI
    KwYBBQUHMAKGR2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvbXNjb3JwL01p
    Y3Jvc29mdCUyMFJTQSUyMFRMUyUyMENBJTIwMDEuY3J0MCIGCCsGAQUFBzABhhZo
    dHRwOi8vb2NzcC5tc29jc3AuY29tMB0GA1UdDgQWBBQg043zGYMPq0QyD3RsvCyp
    gUISczAOBgNVHQ8BAf8EBAMCBLAwggFSBgNVHREEggFJMIIBRYIaKi50YWJsZS5j
    b3Ntb3NkYi5henVyZS5jb22CHCouZ3JlbWxpbi5jb3Ntb3NkYi5henVyZS5jb22C
    HiouY2Fzc2FuZHJhLmNvc21vc2RiLmF6dXJlLmNvbYIYKi5zcWwuY29zbW9zZGIu
    YXp1cmUuY29tghkqLmV0Y2QuY29zbW9zZGIuYXp1cmUuY29tghoqLmdyZW1saW4u
    Y29zbW9zLmF6dXJlLmNvbYIYKi5tb25nby5jb3Ntb3MuYXp1cmUuY29tghwqLmNh
    c3NhbmRyYS5jb3Ntb3MuYXp1cmUuY29tghgqLnRhYmxlLmNvc21vcy5henVyZS5j
    b22CFiouc3FsLmNvc21vcy5henVyZS5jb22CFyouZXRjZC5jb3Ntb3MuYXp1cmUu
    Y29tghUqLmRvY3VtZW50cy5henVyZS5jb20wgbAGA1UdHwSBqDCBpTCBoqCBn6CB
    nIZNaHR0cDovL21zY3JsLm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9jcmwvTWlj
    cm9zb2Z0JTIwUlNBJTIwVExTJTIwQ0ElMjAwMS5jcmyGS2h0dHA6Ly9jcmwubWlj
    cm9zb2Z0LmNvbS9wa2kvbXNjb3JwL2NybC9NaWNyb3NvZnQlMjBSU0ElMjBUTFMl
    MjBDQSUyMDAxLmNybDBXBgNVHSAEUDBOMEIGCSsGAQQBgjcqATA1MDMGCCsGAQUF
    BwIBFidodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9jcHMwCAYG
    Z4EMAQIBMB8GA1UdIwQYMBaAFLV2DDARzseSQk1Mx1wsyKkM6AtkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAeapIu7Oo
    1VhXqxuAddvdPZFMegkVT6x84opwsKEPE9C5ifKySb8YV0A7Tvy3fBacqP6TQsIx
    GHPAcQsm8N1GRmnNEVre65p+4tdoVR7GzWCUEXeEzNo4qjkHZ3p1VRvOE0fa1OxG
    krdlP2e4cbDQ+JcLDGaEFsLWsqCA2Sac3+qMp27c2sJP5joMvuLBFFNTmmBLSl4q
    hG9wQMesdhmXhAydNcmdBfSbau/6ARFCT0rsn7X0gK6vJaavsRLpkETQIYgD710S
    Ot0wnYlf37VH7QYrVDF7eDlrcT+pfnZFoiVxk8Wp62x/w+nvZgqRPtqDA5tqVuez
    /8a7KjT/3KV+0RQm7pEOxWYTa20PoDtLJvDMGDqYCDTHdYQh+2tBEHaw9CYpz7/Y
    t2XaBRErwMQtuXCVB1XztZYjqaP2TurArx1sEdjlsaztTIeO5c8vyvzcH++V0hG1
    p4jn7Fk6/BD50CnnYNWPg33uj7eH/K/r5BMdcMJzsIkvkita6C0PkiZlzqj86WYS
    uh9TlwLTF3g3e+z32OMM4H41RO+NHfjCDJ4pdY3PbXKQq7LyMRUap/I6o9xLFCeM
    Nsu2lP6l5ui6Z80dCFG1OP5/R2REq3S1BAyYLnQHgWTOkVcowE32NPpscjRBNiYJ
    AjXwgCfx7dIIoocL5fJOK5CToUv1hB31rtyYzhG5X7lhxW2IlFPwBQZzMq/FCQ==
  readonly: true

- name: Azure.Cosmos.Cassandra.Truststore.Path
  value: $(Build.Repository.LocalPath)/truststore.jks
  readonly: true

- name: Azure.Cosmos.Cassandra.Log.File
  value: $(Build.ArtifactStagingDirectory)/azure-cosmos-cassandra-driver-4.log
  readonly: true

- name: Azure.Cosmos.Cassandra.Reporting.Directory
  value: $(Build.ArtifactStagingDirectory)
  readonly: true

- name: New-JavaTruststore
  value: |
    Set-Content -Path "${env:AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PATH}" -AsByteStream -Value ([System.Convert]::FromBase64String("${env:AZURE_COSMOS_CASSANDRA_TRUSTSTORE_CONTENT}"))
    "Keystore path: ${env:AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PATH}"
    keytool -list -keystore "${env:AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PATH}" -storepass "${env:AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD}"

- name: Stage-Artifacts
  value: |
    $packageName = [System.IO.Path]::GetFileNameWithoutExtension($(Get-Item *.jar -Exclude *-sources.jar,*-javadoc.jar).Name)
    $targetDirectory = New-Item -ItemType Directory (Join-Path $Env:BUILD_ARTIFACTSTAGINGDIRECTORY ${packageName})

    Copy-Item *.jar $targetDirectory
    Copy-Item (Join-Path .. pom.xml) (Join-Path ${targetDirectory} ${packageName}.pom)

    $packageName = $packageName.Split("-extensions-") -join "-"
    $targetDirectory = New-Item -ItemType Directory (Join-Path $Env:BUILD_ARTIFACTSTAGINGDIRECTORY ${packageName})

    Copy-Item (Join-Path .. .. pom.xml) (Join-Path ${targetDirectory} ${packageName}.pom)
  readonly: true

- name: Update-GithubSubmodules
  value: |
    git submodule update --init --recursive
  readonly: true

jobs:

- job: Build_with_Java_8
  strategy:
    matrix:
      Linux:
        ImageName: 'ubuntu-latest'
      MacOS:
        ImageName: 'macos-latest'
      Windows:
        ImageName: 'windows-latest'
    maxParallel: 1
  pool:
    vmImage: $(ImageName)
  steps:
  - task: PowerShell@2
    displayName: Update GitHub Submodules
    inputs:
      targetType: inline
      script: $(Update-GithubSubmodules)
      pwsh: true
      workingDirectory: $(Build.Repository.LocalPath)
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'install'
      options: '-DskipTests'
  - task: PowerShell@2
    displayName: 'Create Java truststore'
    inputs:
      targetType: 'inline'
      script: $(New-JavaTruststore)
      pwsh: true
      workingDirectory: '$(Build.ArtifactStagingDirectory)'
    env:
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: Maven@3
    displayName: 'Verify driver-4 extensions'
    inputs:
      mavenPomFile: 'driver-4/pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'verify'
      options: -Dcheckstyle.skip -Dmaven.main.skip
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
    env:
      AZURE_COSMOS_CASSANDRA_PASSWORD: $(AZURE_COSMOS_CASSANDRA_PASSWORD)
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: Maven@3
    displayName: 'Verify java-driver-app example'
    inputs:
      mavenPomFile: 'examples/java-driver-app/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: "-Dcheckstyle.skip -Dmaven.main.skip -DargLine=\"-Dazure.cosmos.cassandra.jar='${project.build.directory}/${project.build.finalName}.jar' -Dazure.cosmos.cassandra.log-path='${project.basedir}'\""
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
    env:
      AZURE_COSMOS_CASSANDRA_JAVA_OPTIONS: $(AZURE_COSMOS_CASSANDRA_JAVA_OPTIONS)
      AZURE_COSMOS_CASSANDRA_PASSWORD: $(AZURE_COSMOS_CASSANDRA_PASSWORD)
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: Maven@3
    displayName: 'Verify spring-boot-app example'
    inputs:
      mavenPomFile: 'examples/spring-boot-app/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: "-Dcheckstyle.skip -Dmaven.main.skip -DargLine=\"-Dazure.cosmos.cassandra.jar='${project.build.directory}/${project.build.finalName}.jar' -Dazure.cosmos.cassandra.log-path='${project.basedir}'\""
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
    env:
      AZURE_COSMOS_CASSANDRA_PASSWORD: $(AZURE_COSMOS_CASSANDRA_PASSWORD)
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: PowerShell@2
    displayName: 'Stage driver-4 artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/driver-4/target'
  - task: PowerShell@2
    displayName: 'Stage spring-data artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/spring-data/target'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish staged artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'driver-4.java-8.$(ImageName)'
      publishLocation: 'pipeline'

- job: Build_with_Java_11
  strategy:
    matrix:
      Linux:
        ImageName: 'ubuntu-latest'
      MacOS:
        ImageName: 'macos-latest'
      Windows:
        ImageName: 'windows-latest'
    maxParallel: 1
  pool:
    vmImage: $(ImageName)
  steps:
  - task: PowerShell@2
    displayName: Update GitHub Submodules
    inputs:
      targetType: inline
      script: $(Update-GithubSubmodules)
      pwsh: true
      workingDirectory: $(Build.Repository.LocalPath)
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'install'
      options: '-DskipTests'
  - task: PowerShell@2
    displayName: 'Create Java truststore'
    inputs:
      targetType: 'inline'
      script: $(New-JavaTruststore)
      pwsh: true
      workingDirectory: '$(Build.ArtifactStagingDirectory)'
    env:
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: Maven@3
    displayName: 'Verify driver-4 extensions'
    inputs:
      mavenPomFile: 'driver-4/pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'verify'
      options: -Dcheckstyle.skip -Dmaven.main.skip
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
    env:
      AZURE_COSMOS_CASSANDRA_JAVA_OPTIONS: $(AZURE_COSMOS_CASSANDRA_JAVA_OPTIONS)
      AZURE_COSMOS_CASSANDRA_PASSWORD: $(AZURE_COSMOS_CASSANDRA_PASSWORD)
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: Maven@3
    displayName: 'Verify java-driver-app example'
    inputs:
      mavenPomFile: 'examples/java-driver-app/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: "-Dcheckstyle.skip -Dmaven.main.skip -DargLine=\"-Dazure.cosmos.cassandra.jar='${project.build.directory}/${project.build.finalName}.jar' -Dazure.cosmos.cassandra.log-path='${project.basedir}'\""
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
    env:
      AZURE_COSMOS_CASSANDRA_PASSWORD: $(AZURE_COSMOS_CASSANDRA_PASSWORD)
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: Maven@3
    displayName: 'Verify spring-boot-app example'
    inputs:
      mavenPomFile: 'examples/spring-boot-app/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: "-Dcheckstyle.skip -Dmaven.main.skip -DargLine=\"-Dazure.cosmos.cassandra.jar='${project.build.directory}/${project.build.finalName}.jar' -Dazure.cosmos.cassandra.log-path='${project.basedir}'\""
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
    env:
      AZURE_COSMOS_CASSANDRA_PASSWORD: $(AZURE_COSMOS_CASSANDRA_PASSWORD)
      AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD: $(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)
  - task: PowerShell@2
    displayName: 'Stage driver-4 artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/driver-4/target'
  - task: PowerShell@2
    displayName: 'Stage spring-data artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/spring-data/target'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish staged artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'driver-4.java-11.$(ImageName)'
      publishLocation: 'pipeline'
