# azure-cosmos-cassandra-driver-4-extensions build pipeline
# Builds and runs tests with Apache Maven.
# Reference: https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop/java-driver-4
- release/java-driver-4/*

pr:
- develop/java-driver-4
- release/java-driver-4/*

- name: Azure.Cosmos.Cassandra.Truststore.Content
  value: MIIgDgIBAzCCH8cGCSqGSIb3DQEHAaCCH7gEgh+0MIIfsDCCH6wGCSqGSIb3DQEHBqCCH50wgh+ZAgEAMIIfkgYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUOJx4WcNXiCuB+c2lbaYi33xNQR8CAwDDUICCH1hCVbZ1htiLMAUXYhSo8DPf9+eu+VCf47EC4Kvj3vnDGdocDeTQoUVyvsmHpjLuLO13s4K7W8JZuuktnPOqZSV0QMrOlSNCz+RoudmaUyZA+ks4pZftfUiw8Spr94C1myYGqopWJtm4B+ikfZhTiWcekkwz2KbVHv55KNeEzbLYMDfkv1rvw//a1OBBbyQi5jiRtb7HSG+CGtfy7v65/X+ijLm+2tzgGF4IFztldWsXqmqtS+ntbrpa4Ag7KpfdyUbyh4l7shOrsUQ/SFt9qSrhSaci4bi6aumPTc2l6EvWwOEdEOrHxPZ8qAoEtDhk5VUakRXNQyJuYykuScpkTsrst0y2zVErpTlSypYtfQOlsm0mbKEz/7B1P56USKYgZZPG59n1JVquyxGsXeCi4JZddbKFqg6RFQNxNhZruAosFmFGckERwqJZJuvH3Sa+U14ZlVK8lymKr8BgOvsDyjXGexPCQ7PIg82uevkKBqHL4La7TQc7fMXaZ6Wc9PFey51SZFaRNpryAW5hqmxIiTZx4HO73+8c7EM1Vh5J5bx0JNsi2dPyW+iPCVqlVWyAhHORpSrgiQUG6cNThORsuKH7WFec0as1+dt1RyphnFoT/AQONMQyaYFXmxceEGF1Wf19GslllGd2nhWkRKYSgP/klxhpCHFpujshb+gQsT8sEIPn++VXaQ5+bfTTLs2BWxWayP+FSvUYFr1nD3Giuilu4sdVnLL/UY/yma48ax2VqsJ7H8pQl1Sg/JSp8hqF0LG6lvZimYY8lxEixRjhlQk12TADadH+xNWY6bZl/VSfap7G7qqzEKxVi8aHfxYtpqylkkRh7lU6SOoH0OMgbz1rl6bb8Iirmukm/er0HvSAwisZDMnhM4WSdoM0dVPoQDHpnf+yHC6Q4y+VD0mJ4sWTPyrnfsRlFeLe6NlLEImwg5sL9IL/KJliLAAoHOsEQSmVL71ggTLj5ZW3i/XZaiuhcxqDEcWV+XvgcdGh7EAq7MCcTe6ntMWwHcq8oTkPQ5b3sOlDDZBdmItOdwOzl4so+92FxYgT5DJYIoHHAPHP1RrT005aH7KSgC+sUQJaV+vnNq2+Q4ZYy1JtA9Wcm8/fRJh8KCGyHrts45OAQKROctbwHCu4tZTCh/sLUu4V0BchBxMGRaAkG6W5e8SufM0HhbB6B7Jrd7mtPbCMku0cacdMXb9ixGhaqbQJL2srbrfP0XKLS349xCEDNHAbKaMPLA+7r7w6yvlskKkc4x/917YWGnAoL0FCs2s4JJFqpuUXf/ecFMPEHYxRkJhHzQ4rGGLC0WMeSek1VhFOQSwQkp1jTFzq7Kh7BLp8vYgt09qbGZzqFDEvMJiva4JDCBlJ+kaVxgvb3eMW/tPEzS0D9xy4WwfK0Jvv9k/2PQRkK8vNCWpIsTzkjeAspeJB+AJxORWwFmIsiZ3rQ4tkbG2GNiuDI8CkEhVpdDJr/uN9AhQd5HXn8DBMsu2tFQMoejPDfzj5rLYT7d34Yj3s7Zv+VhWOPg/aPUy/CTHYl6xPZsuDc1Fk2cQAYpJjavoaXNBYaxCJ5PpbW99ALX2dUEeMrT5qMhfVvXRWcVnrPcQtcQrf7Y94123rsURLAQGyfC+isM7J06u5aYwhW2OsqHOPhjY2a4/M0mbuj6OwSLIMb1NVjz8f0uH3z9cvDW1NNNDQQlpIW5Y1i0kjtD6I7YxZk75qJiTR9F/LDtRW/H1NPrOcty55drar/eC7C5dGVMUuaVaRIvr+9rHJfDGvVZ5xuyEB+v//Xqgk5wzhRDlRcUVtGK4KAgTqkah+dsekVdHBXOtnPAO68bFcgFFAx4aYykACbf2gtixnoswoEpatm+mjOYlDj5/ibRRpDLJ0aVVZfcbBia3Vc+YzjjFUhNZH5Fpg8dF9poYj7IvJddHBUW2SKYP0SHa2gnSXMBvACV6aTBcEHBBx96PgjH47zy1MtL7+gBMwt3yX7uPbdmCgL3xL6SJNMxT2JgX55LrAGdppu6/dUwxkysEsJwWAM5uIo07/GxIqMNbnFCC+2m2B8a/PPuIY6lWr6Jyl7+IVls9DPMUItEhjjG8ziMLxCf1KmJxwtkqrpe55AgBVg43BYBskKsgsQVqPGOhV8B57QS+r7sFkZIkvUcgzul/TupPv4yKrlkV7HNOgXxRUz2IdlUavVi6QvkIg84AprIElYSNuU+d8o5jxXAHJv8rzijnXqnlQ3sLAbU/0ag9zcb8Aje0zfSeaVkJsLYbMVC1gj0iiWfhusvdEKQfda/jLZ6mZBgbB+NaWkeHW9Hqwen8SkeK3B4tojIAA0ibxpJVd0bE0qfRRMSTHZVSF2rk3LhmQcKjYvBhSHmKwo1mpWB5jYtyeH+XXGH8AleGqrxR50Ps+DXjWdOfZiAF+QyNFsJbLj65UXYliRu6RLvRX6+t5XYxJEynBGdtwWJfSPfDBCjSQbStV5wLr86IqhED3muPnEreesE+XGd+q2Pe+O7HAOaTaKInSxaG8Sf4sOuUL16S0swx2sQpMylrXgKHzyo7R5hCWYtq/u2kp/A5vPUICE0Lm91n2bunVk1OAetHBVChwREVb0Eu05lIEwWHsLqQZQXsGsCdaMCWOMiEBqV7rzwTY2fiOZ91uK6n/IM975Arh0qACkt9IKS9dLcvxqnca5RR3oejln6trGl7EMV7PWF738H5QDLBvdGiusj7qAhazXjmChtkk9VORYtAw7aOTD0tFj+cI/WfGE/v7fVAxPyKr5Kq3KgKX+Xt2D4lp2NGFC66xdncCjICFQdEFSZRwEaO4sI/QXJrCW1XDutYe+WWDFFpj1SITwe/BPplyQcQq4uLmr7fULvfhuD/C8Nj2umi4HfVcrxrs2FYzVV5gOubs8yQPrrU6pXdCQT8422Gd3K81fSbvFArSWAK+DOX3C+JPylLgRiWPC/HgPO2eMKdZNdpzTqr9hLlSV4eO6378rOzAzZ5626KRC3tFtIYnp95u8C+2C4DR0lZ+qOV3Di8ip904N63CK3TcuD4a2K50jsLN7kNPhfrTgi9ZHczqgyKHumDoAf5JTqzN9kZAQL5wEzo6x60e/Wuwc5x7ZxG+2IWNVaKzpqk5TU1BfnK148vgWW0dsVKebraG6kigUjNTfi7VGARyu+7SmhNiog/pNEH4RU9rOsEfvWLu/YsHPtrRw4FkOtlQoTImzSq3xDYP86etA8EUea+rdWgzn/SL4yOarcieejG3thWAK2ZW0btunFPiyjXty6iLMmCzzDqUz64hfvZ82gmNFukwnQQyhtvg4dyO9RCVdE/7LNFyANCgCQxFI9BNgtHuU1t1vfXS+s1QGxNswOI9DsvIByyqO8Bv9scnyYzrsNTEnYmsYYZd0MnDJgGy30AevKa3v4zn7iVFnEJZ6WCpufgiGJO0Ml9F80Z3xFw4cG2tuFrkVdo4a/xaJmtaqQ4iLb3W/BmxvNkUwh4rjpze8ZT2rbs6hGFZeF1PbTamzrPdGZ9P/o30flqcISs6FQPsIabWjYSna3qaVxQ+PhSMUH1LPpUMbluUVO5C0lovQqoKqqvHTb49fLVDDPX8E/nmxjPr313w5LX0piGj3/+hkbKWAIg4ordcU48gWpbn5jkeLlfjjQ0baZZjtutInZOOWMaHwH7Ljk5MVSdEIyGY55IMBwEXe3tfjmUFIQihS6Y+O2nRz49Sz4HICHjLOi9IWCdWYVuAlVJlXeWPLRnSbOYSImzlvST/wCUuTYSRfJbd1jBeyE9BXedFZK16yrE/fUf3dwspp88dGepYMp96aGaTKtC6cYT7xnSJacWWx++Jch7FkqK6XGRdxIVBkQKYlgFHF9vSI5PzGvdUNSgSDtzAt7TjHyF0k4uAx9ZIUqVaf/k378a9Wnwaelq8oEEqEu1HmnPEIFNrh87R/smf6KrEcbNloopOk58GnjMVzbicy/KniwJkdN+9zjWYYhoAFo8aaJ8Y0JdGbGtRGtpXcTaC2uh1Ey8WA2MxpZ6EyUXODHCSPMZIPAdww9W0Cu7juGu1ka8Zpa/pjU7OWSfkS0peytSIyZ6ZAi6HAUP7ZyL6N3GHm0SbTWONXZdjN3zKFXrEiq21ajpD/NLlsmztVdqwGTlyPY/CDUT4KQCJwMDF9I7hOazwXp6z1ou2y++qETYPoydcwaIkmHCUuEP4ThfsuQPxOBjxrpEb7EqjDmEVsG0t5/wGgDeUCrnFGjJcpskEdNjhyzogaK8Nvd4PSqS55iwHlqsnwzUnmhSoNYID9u855kp9qDileFpbNwLj2Kw7SXq8nrxBVJisEn49v5Q5E3kk9ISGhQg1bWrqiqIvKl62HniGv3ERmgDLcHQeT6BfOMUs1oHL02fyRN4hSWfkUJna4KZpU5tzKpq+gCc09GyNZMNXPM6o4uD2fPMxuSOSE/T7aYg9ZwNnlEqwChRJ1iJRo0smoviV1+3GgHsoekQ0jwk5hv2U753u3NRNPIrE+okO/j2KdjdvKpo2rE0d1fpSfgkTb/hhJePf5olndcHYx5sNBngNciWInmizgzUtu/PVxuO3prx+tK19JGUYaup3mwiMTtR3P1NBQO/kc8w0iL4P69tHc6YAhYyVTHjKLfBoQ3N7BHXszsGxZGXOg0p4u3pptCANos373Zn+ZSSGBs0M1ohrSGEc8+1hf0XtakNb5RS18LTR0MR2vYro1zxCGty5zgUH/oTuLgdcM0rCjukku/0B9218XELSWgy7tS2lJGoMf5kTXOjnemepJV19yQwzQy+dQt1XcJgLNutunPc3y2Pbb3TMn8COCU0jpNyLJ3XbtWnmfRdsJ2Med4vHqTTo3/owPNYrDVnGHY4LDjbe/LQUO9uJeQWmh9dN2390uNO8La1YVrgQPNZ8Edk5qsXIDt9lIAQUrEJFvPwYiaUn4qlN/PjOKhSCsVgJcC6By3EvntTLKpf6ZuzRmlrGSgUJxlxUZqlzvUMK7e+keOeQHK64xE/CKIyhW0aPe4JUTDW4jHrImrNweZOuPhlMQwnkofJEncAQUJutFfguI69SLgNzh0F1si6n0RD6QKzUyF1/+dbkbBLDXgkUOqF2s7mKGU2MGK6MeiMBI8aj0xu5T8VDAWvmhVyiZSSNbC89AVqxvRka4NRwTm9QFqpmKSMGjzs/vXlSL6zGoWH1x7A7PUMuaazHXncmStRDNjMTqxp32lJEYmpKSUYWeHhvILCIXGoc254X0zJ0i4+iU+V6ZbQPBGtacRz06i2m1ZyiQ1gfSSeG/LrUKhofFht4J5NoQtN7Jvqc4KJPyeYJj2r16zzjwxMIc/zvxy9bnknXiT7eIgC6HguU0H8HyCEU4l5lfTp/VHIkt5tBviIoK2HG+qqtRTYTBdTSHJyO1kjQStN129C2/q3C7NSnJzDYWivXSRMefOEt4OirDrWbfRtH9tfWM8OtnwUGlWiQNnJw8OfoUD2X1LRBXOiz/aQECwUH5LeNetmJpjC1KME198ihUBqwvdrtjw+leS/5RjNQAGDZ3Q6gMW3L3Ojqyvc5NzY25fuUTkBl2eb4SveJmT7SasPI97oirlp0XZqyESfNaqk+7q2RL9P2rW3ZTlXtqI+TNWhGGKcAlL/s3LbJUTOTzVpadSp6lsesa4+fze/ShVUe2dnhO36LtIU29QtXyl+NkNJ4il/UqcEOSCvp/oHmkY1QIzOcVqs83Sujnq035RHI7WFkHca01CGhvpA6TGQfyjxjv3KhhJbGoYNleFMZFrwQdwAUw9sSQu3JbXRb7bZJw/ozIWT4qf3lkCqK0jGXLUj8IXwdIs2Jf4j/YeUF8oR7oE+jd0igsg9mnV9UAXD2MNogPwAgQm0n5WikPUfwJBf5UBZ5aOpJZLh2TjN/jE6J/OVd01ySXQdgwBmIQhWu3bihdyQCepxGWdLK0e3QhCqPob/M1Ogxk3iD5NKJk+LKkNFqhJ098f8Qh7KorTdDeznYWKaSIqjk2+HmwD8KFpzrqlh0u/GDhaVZJ9q4SzdskdZGmb34ZmCl3y//4i/K5F6J5D0hXVgP2Mt8UoJP0ku2NZQT+5MYtUn+gsGEV0UJPp41MMljOdYWiHnVczysm17WFz7g5t8CDteYlFx4cH7ORwMgq1LltSWa87juzzg8MHOTZB2OOmmHB6+DVyqopEzqdm9KZUey/vo1reTMWKO3GQ2BHmawwn0ZdOLtJNgJ2C+oGzBgeU65MBhl0y0WKcL7fpi4KWT6p0JEOSmEaQA3FPLtTAEfMYto+3ljsj56QCbL0u5ihA97O1KGvkcTrsOkMMbH/z1drTSsZNwk0f/qPrBHYMI4AXbO847ctzHFwdkIjPCA9pawOK9779ZlAGqryo4Clr/qGOn5gJcFvCZaPzio3A/EJA7ALZu5QKUFlj1ZDel8S0q3s/wMoEPCZuNfZIQm57GYUl/H/hDt2l9O9UM7f5APaezGZ+oHvCESIsbEOIWEANmXkpCtoCHnI5WOQS6A65rt7T83HrmDY0SM3PjDQPr5JGdADOQ/4ZhV+0cnxW8plyoS0m1rBJH4tySSW4wQdpYZoXzq5QEj50KxYQjEzfXAnBijmyUAnuh2LlKFrU6V0uBGLXnGccH0EwNooZO3ExLYrQIWxfM56q5Pn7GL5zAmpz3q+c7bvBZ7P9bPHxuKVvaIWT4E/utpxczqU3Yha6N7CSy361paf6fcCAs26o+xErJ/1pp/cuNKUV0irM0VB0Ic386P/evOMX+KDXv47yBmkcBwiAoIsx0tTXt8+5mCgaNTGDAWfiKrgMa1jNHmDVHahgTzYao9lK6v1fxo/hnM+sco/or50zKKSYm19gZRTx+S3XeJH62xL8aOy8OeH9X0HAf+zKYmObun4JQTOEbdUFx7d0l5QCdcNRCC+fXu7kTkM3UEd4qdIL1aENW7Kks93MQj8FVGfiUEQI8SqxH1h7fp1q5VYD3iD9lSrk63OpP61g5AaHRHOLvS5t6MOchSadGAOzE5xnx5yGu3B8Ia3jou2byuyaCAqrOuWoGtZRCVblAC8atOsUe/gq8as0DBIVjZ0X5WPrrdxYqm+GPfxHHfOIKk9dtgTMrWUD4m8UaqaRd4Gb/Icxq9TU4Ah11Cyn2noGaJK4dV90t+sEVRKacU45z1vOcNIQlprAOfNH/p+nIt37999Qja4cL9pUd1yZXQNoNVOwv83F/7f8WPySVuVzOldMiOH6jNHs2MyTbWYtbrS/S5DDzUUcgFZ6TwQ0oN7NeOnZsiLKBByqbOCewHH3PxGDSS4/uDFkCTGD0CnY3Am3gvnKkolgoL/1qiOvGXXbvkUW9MmcNQ9ft6d7OuGeVcYjZNk6v7PrwAXca2YNPoSIIBiJpcZD06WGDRlgpjGHhzmLJ7NsEsVYcL0Ha4psr/KR38/7pUDrI8qXPRrXT/uzyI4S3ZZL+Qe05gb9k1L83Af78OrPMy0WiFCHh28x6sPWkbXAtZTdO4mazi5jhUarsEgx7u8wtFMr7V90IagteuPUTdBAHfXTgOnInUv//g/gZ44600U/N85hWIgFELEtwjPXolmYAohYJ8dJHZRobqbFfFDIowXZz6ac91/nkNbdZPrGpOEGSAN85385CPLl+N3qAI+C8cs6NQCW4W42knUz8e28YDiuNwJLp1v7qp3+st5HAqzOOFdstVIPfL//t97fRk9KQ9+5FdEHzHd121pLbsdprt4YmBImqhZWX4rbz0XwPVHu4nf1bC6nIXQ9uR+qo8r5mIu0dQeNdSox3hJVWU7uEiNoGMQWKW5FGBVUabC35qR781aPiRSwjGd0kw9XIR1sjCAlDmCkTj8U6zhI/u6e7bWSleOvc/xjaWl3X0mXdMcnOb9wrwzpOgUYfCH19Pn4P/2vDcRD244HZ+mIBGWNPrbCkU+V1mAN/+HFSuSzUsHDdedORarOMpm5HQp8rw4Hhk6QPyYeBuomevXTGyo+qb69GovvI8nbpyO+8S1BM9SBYKZTfMejfhQkrGoFoED7L0qaI+7ZS4TSeYZzgIqx2iP6ybkxPT/kB2scp88/kvB4e/QiKZSZihklZ9lVLDaJA1dylh2JXImZpD3MulCw6nJGVfD6AQbWcR0zPDf3KO9NHdiEeVOGB+v6+Y2uFUPyvyTSL5Tbt4c6uCPqgF+FcetW9o7MCxyqLOxWim02JjqpniazL90WYVfl19sQ/EyA/hIes6Reh7iBoLSjMpgEbcpGwrlF8lt4LYvC9B828uJWTpKk+cEHpkMYk4CF9+hvHVpyuFEMDARZ+hCYCFuQlEyXJPCMh6LPpWQ8V7NNny9dr0FrFdRbvEveaME2Gclw6oWrznnpMZhRkubqXUuvvOQdUHz9zer1IJkkRJSrxbRi8Gxwb1lp0/7pzth+Hcpvgz8qC8d2MF+LslLNcWuLopunKZw7sj+GQIcem/NrAMR7mZoBOymAqSBBOCcQnJE/J9+w43pbkOSsTZjSreTJR+WCL23btN5AvQDxdSM0XUaweoIvH82gan/PD92NmEDskX3lKSEv23RDWaGXj3FXucDKl+fFEgO2U45ir5a3Mur/d396jsPAxFG78oOMxMoHjalXija7E3VDt3AjygrA7lPKI4/UHnXp4GVL3OO8OeytaiQrGSqRyLMGoQK5OzSNh14TY/Adv1u96Jo1j1rRKhtJxIyLrZ6Y1oPtf30O4totDr3G4KiMHLmYBPE5e+EaJ+J4kCxsZDD5xqU1+rbwHIZWfSVvr6H3Ucwlv6AYvhh+TkMFQhxjHqXYRPv7sR1wYJ/Hp2FHxF3OlbddpyYBSmJhmZ0LN7sGtaudR1P5O70WdbPs/Vj21fxfo1bs0FgXZBQ5XJ2aqzgIPSDxo4B83h3BPBmBGgIoewBGK3v/JO2AYg+eYcTgf1ZLPjUs8br2Hxw+Q6SlggzXowfQQAhx/y+OeDPhNNwkzy4lOfkL1hMnQODsEw5xylb2KFa4aa40xsTwJZv7aH9N741oy1DY+dQlwsfYOD/cI5cWxK/N1CRgAjaCEQucpmVynnjma89/6i0afmVAOjTCs5fNYiJhP9SFF0ZTH/46Tq9E/1yLKRKyBfJk7lFyl8Fg8009KbaZbs11D3X6GaWq+cySg5fNSOaQfnHsm07yBepmF4e5d5u332G+0G8Fyl9wELKz8pBwgz5Oxt2WG/NcPaThXUCEgqOEix8Fwavyw4gsNartiU0El717RHUFF8CzRve/dubz64uKFS07JowN7yqclxM72dEDRu+wyHXh1/T8FgQ4xESkiywEm0zzJ0q9+e57L7nMcnnGQMxQjSAtuK5T2S9Pp6GnFjDOT1FCPV3OqkI+AI5GgN0ID6iDlcuiWSz2F/ZXyOHAotCvbkGGHhmUJxl7V2c4hn+U6RkeZZEyFiajE2covtCO3T6Sd6CysYny1EGxiTYYmb5gY9i7psIuMffnFUM+ZogoKg6mFoQ9nsE9OmHrcZrUdZaem9jf24dVtHDyur8Xx2vMkM1MiaLQJkILN6BMpGPcWevIUzyyGKzSuvdCPENAACM2bWfCPoAF1G0pD8fuN6Q6QcdeBvlH99+XNw5PO+tPsUWJcTzv5RrmTpF4OyKG50l+VQ5jxVFDeC+ilyOS1UT1vhnnVRtV8jlfknpYFtLVulpE3P0KU7YEoZ+y52swGvIenwUFq793cpZrqLOD+qS+e186/Qh8xxKWd52pXF6ZakhZ6znCUD/hh/NDvlzSyu1LmHJFh+dq4pUVSqv46/G9axOAhPHlF/DNT3UD/QPDc40GcZum/JU5KJ+3eY/EXqQKcbclBlEiI4tC1v7ZCKrH84Ucbdjq1dUDb7peuvClii/bpxU0FGAA0GYRvMAEmp2mvwZy+cSYCyGX2cb04dprr/+8ngtiCqC+WpJqlLKJVbB7sVsF269gkh3BVtgnY/K3dznzHK2e/wYlLIUs/4PHgXvWdVauL6rB0u/KarNH/ayXalvPj7cVQS1IvPL8E8iqP6VBXOzz26D4j89pfQunwHr/zZzH4DxPmYU37ccAZRunLCpL1YebKOJm3LSfqqdK8LPU3Nd1US9tW88tgfUK9F/Hw0FG1m9Lf10VLskdOIoG6zJFTMopOTXcu9DE7YV2mW4lpTVEbJsDdLZ2pdAkTERgmythqjFRKFzQ7GP4yvDirYv2rxotZdOHOr+m3kZPsm46d1PYYM89+1VgzbjNM6Y7QLORgo1Hs5UdNOjOIc1kAJjn/NczpJmPSZxobFlDg6KxmbIkfZNQwed/Oy2BdJR4eUIhek9OOhMcGDHG2w4ZTrvgRb/k4RKARMgPsUpn3JnSSXMbrAs2Cxy+sIz8lOPrh+WJOChUJMU/xTFXvxeL/kZMrhH/sSqGTm8/zW+zcuNgFbGp6MIpzpbczanDt+oWons2poaBV9rdcg6Po2dByKg9Af5tvRHIxB99i1J7w1W3IXzzhIb+AIJbBq3z3NqnjKEYjkXKWlMKBSupaPCk9JyegyoXf6c7BjDxtEA0JXfAkYVA3gSx1lVg+8/CmvBMr628vGkP9v8+UvmENOMFlnoZVfAt5tyy57jtTE2qSFnDDMySaclXr99SIvy3xML0STdnL+xQjD0sn8V2ROadzqtTPWOdqIuN6O/ApMVPFailw+8kELQHcjXg1XJT8+TEaXM6ClPrUhiuK1M/l6KLhhTAxipYjXo7eR+C7wScCzMZeCNEUGi5pk3FAea1JWK2nhiurHBTA+MCEwCQYFKw4DAhoFAAQUUjiWJkfP7+ADb8vWJAEEYOY3POAEFAjN/f843COs5lmw8qNpbmjChaRHAgMBhqA==
  readonly: true

- name: Azure.Cosmos.Cassandra.Truststore.Path
  value: $(Build.ArtifactStagingDirectory)/truststore.p12
  readonly: true

- name: Log.Filename
  value: $(Build.ArtifactStagingDirectory)/azure-cosmos-cassandra-driver-4.log
  readonly: true

- name: Maven.Surefire.ArgLine
  value: >
    -Dazure.cosmos.cassandra.global-endpoint='$(AZURE_COSMOS_CASSANDRA_CONTACT_POINT)'
    -Dazure.cosmos.cassandra.hostname='$(AZURE_COSMOS_CASSANDRA_HOSTNAME)'
    -Dazure.cosmos.cassandra.port='$(AZURE_COSMOS_CASSANDRA_PORT)'
    -Dazure.cosmos.cassandra.username='$(AZURE_COSMOS_CASSANDRA_USERNAME)'
    -Dazure.cosmos.cassandra.password='$(AZURE_COSMOS_CASSANDRA_PASSWORD)'
    -Dazure.cosmos.cassandra.preferred-regions='$(AZURE_COSMOS_CASSANDRA_PREFERRED_REGIONS)'
    -Dazure.cosmos.cassandra.preferred-region_1='$(AZURE_COSMOS_CASSANDRA_PREFERRED_REGION_1)'
    -Dazure.cosmos.cassandra.preferred-region_1='$(AZURE_COSMOS_CASSANDRA_PREFERRED_REGION_2)'
    -Dazure.cosmos.cassandra.preferred-region_1='$(AZURE_COSMOS_CASSANDRA_PREFERRED_REGION_3)'
    -Dazure.cosmos.cassandra.regional-endpoints='$(AZURE_COSMOS_CASSANDRA_REGIONAL_ENDPOINTS)'
    -Dazure.cosmos.cassandra.truststore-path='$(Azure.Cosmos.Cassandra.Truststore.Path)'
    -Dazure.cosmos.cassandra.truststore-password='$(AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PASSWORD)'
    -Dazure.cosmos.cassandra.log-file='$(Log.Filename)'
    -Dazure.cosmos.cassandra.reporting-directory='$(Reporting.Directory)'
  readonly: true

- name: Reporting.Directory
  value: $(Build.ArtifactStagingDirectory)
  readonly: true

- name: New-JavaTruststore
  value: |
    Set-Content -Path ${AZURE_COSMOS_CASSANDRA_TRUSTSTORE_PATH} -Value `
        [System.Convert]::FromBase64String(${AZURE_COSMOS_CASSANDRA_TRUSTSTORE_CONTENT}) -AsByteStream

- name: Stage-Artifacts
  value: |
    $packageName = [System.IO.Path]::GetFileNameWithoutExtension($(Get-Item *[0-9].jar).Name)
    $targetDirectory = New-Item -ItemType Directory $Env:BUILD_ARTIFACTSTAGINGDIRECTORY/$packageName

    Copy-Item *.jar $targetDirectory
    Copy-Item ../pom.xml $targetDirectory/$packageName.pom

    $packageName = $packageName.Split("-extensions-") -join "-"
    $targetDirectory = New-Item -ItemType Directory $Env:BUILD_ARTIFACTSTAGINGDIRECTORY/$packageName

    Copy-Item ../../pom.xml $targetDirectory/$packageName.pom
  readonly: true

jobs:

- job: Build_with_Java_8
  strategy:
    matrix:
      Linux:
        ImageName: 'ubuntu-latest'
      MacOS:
        ImageName: 'macos-latest'
      Windows:
        ImageName: 'windows-latest'
    maxParallel: 1
  pool:
    vmImage: $(ImageName)
  steps:
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'help:active-profiles install javadoc:test-javadoc'
      findBugsRunAnalysis: true
      options: '-DskipTests'
  - task: Maven@3
    displayName: 'Verify driver-4 extensions'
    inputs:
      mavenPomFile: 'driver-4/pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'verify'
      options: '-DargLine="$(Maven.Surefire.ArgLine)"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: Maven@3
    displayName: 'Verify spring-boot-app example'
    inputs:
      mavenPomFile: 'examples/spring-boot-app/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: '-DargLine="$(Maven.Surefire.ArgLine)"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: PowerShell@2
    displayName: 'Stage artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/driver-4/target'
  - task: PowerShell@2
    displayName: 'Stage spring-data artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/spring-data/target'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish staged artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'driver-4.java-8.$(ImageName)'
      publishLocation: 'pipeline'

- job: Build_with_Java_11
  strategy:
    matrix:
      Linux:
        ImageName: 'ubuntu-latest'
      MacOS:
        ImageName: 'macos-latest'
      Windows:
        ImageName: 'windows-latest'
    maxParallel: 1
  pool:
    vmImage: $(ImageName)
  steps:
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'help:active-profiles install javadoc:test-javadoc'
      findBugsRunAnalysis: true
      options: '-DskipTests'
  - task: Maven@3
    displayName: 'Verify driver-4 extensions'
    inputs:
      mavenPomFile: 'driver-4/pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx3072m'
      goals: 'verify'
      options: '-DargLine="$(Maven.Surefire.ArgLine)"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: Maven@3
    displayName: 'Verify spring-boot-app example'
    inputs:
      mavenPomFile: 'examples/spring-boot-app/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      goals: 'verify'
      options: '-DargLine="$(Maven.Surefire.ArgLine) -Dazure.cosmos.cassandra.jar=$(Build.Repository.LocalPath)/examples/spring-boot-app/target/azure-cosmos-cassandra-spring-boot-app-example-\${project.version}.jar"'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      publishJUnitResults: true
  - task: PowerShell@2
    displayName: 'Stage driver-4 artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/driver-4/target'
  - task: PowerShell@2
    displayName: 'Stage spring-data artifacts'
    inputs:
      targetType: 'inline'
      script: $(Stage-Artifacts)
      pwsh: true
      workingDirectory: '$(Build.Repository.LocalPath)/spring-data/target'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish staged artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'driver-4.java-11.$(ImageName)'
      publishLocation: 'pipeline'
