cosmos.cassandra:
  base-packages: com.azure.cosmos.cassandra.example.data
  contact-point: ${AZURE_COSMOS_CASSANDRA_GLOBAL_ENDPOINT}
  keyspace: azure_cosmos_cassandra_driver_4_examples
  schema-action: CREATE_IF_NOT_EXISTS

  auth-provider:
    # By default we use the PlainTextAuthProvider (see reference.conf) and specify the username and password here.
    username: ${AZURE_COSMOS_CASSANDRA_USERNAME}
    password: ${AZURE_COSMOS_CASSANDRA_PASSWORD}

  load-balancing-policy:

    # Cosmos load balancing policy parameters
    #
    #   Update this file or run this example with these system properties set to override the values provided here:
    #
    #   -Ddatastax-java-driver.basic.load-balancing-policy.multi-region-writes=[true|false]
    #   -DDdatastax-java-driver.basic.load-balancing-policy.preferred-regions=[<region-name>[,...]|[]]
    #
    #   Alternatively, set the environment variables referenced here to match the topology and preferences for your
    #   Cosmos DB Cassandra API instance.

    multi-region-writes: ${AZURE_COSMOS_CASSANDRA_MULTI_REGION_WRITES:false}

    preferred-regions: ${AZURE_COSMOS_CASSANDRA_PREFERRED_REGIONS:null}

  retry-policy:
    # By default we use the CosmosRetryPolicy (see reference.conf) and accept the default configuration here.

logging:
  file:
    name: ${AZURE_COSMOS_CASSANDRA_LOG_FILE:${user.home}/.local/var/log/azure-cosmos-cassandra-spring-boot-app-example.log}
  logback:
    rollingpolicy:
      max-file-size: 10GB
  pattern:
    console:

spring:
  main:
    banner-mode: off
